### ISSUE TITLE
Add --config option to pass a json file that contains option list

### ISSUE THREAD

**Issue by Genne23v** [cychu42/staticSiteCon#13]
Adding a new feature to provide a json file to pass option list to execute. For example, 
`... -c <json file path/name>` or `... --config <json file path/name>`
Passing json file has an option list in a json format as below. 

```javascript
{
  "input": "./site",
  "output": "./build",
  "stylesheet": "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css",
  "lang": "fr"
}
```

When the file is missing,  or can't be parsed, exit the program with an error message. 
The `-c` or `--config` option will ignore other options provided in command line. Also it ignores the options that are not supported. 
When `-o` or `--output` option is not provided, it uses the default folder which is `./dist`.

**Comment by cychu42** [comment]
It would work. I have my variables relevant to this option placed around line 9-12, so you can set those and add new ones there, if applicable. Eventually, I plan to place them in a config module when I get around to separate this giant block of code in SSC.js into separate modules.

You might want to add the code you proposed a bit further down to override other options. 
For example, if you just put the code there, line 253-255 for `--stylesheet` option would override your code for the JSON config, as far as what stylesheet to use.

**Comment by humphd** [comment]
Looks like this didn't get closed when https://github.com/cychu42/staticSiteCon/pull/14 was merged.
