### ISSUE TITLE
HTML pages generated by SSG only contains `<p></p>` tags

### ISSUE THREAD

**Issue by SerpentBytes** [cychu42/staticSiteCon#3]
## Operating Environment

Operation System: macOS Monterey
Node version: v16.17.0

## Browser Information

Firefox 

## Bug Description

The static pages that are generated by the tool only contain `<p></p>` tags in the HTML markup. 

See below:

<img width="1279" alt="issue3" src="https://user-images.githubusercontent.com/50856799/190284458-696054f6-886a-4ff7-b69c-cff6e0c1c880.png">

## Expected Behaviour

When viewing the source code of the page generated by the tool in a browser, the document should resemble a standard HTML document.

## To Reproduce

1. Open a file generated by the tool in any major browser
2. Right-click on the page and select "view page source" from the menu

## Potential Fix

- Make use of [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to store HTML markup in a `variable`, and pass it to the function responsible to write to output files. In your case, it would be the `outStream.write` function.

**Comment by cychu42** [comment]
This feature is updated to generate files in html standard format.
