### ISSUE TITLE
Add support for programmatic generation and deletion of the `./dist` directory

### ISSUE THREAD

**Issue by SerpentBytes** [cychu42/staticSiteCon#5]
## Operating Environment

Operation System: macOS Monterey
Node version: v16.17.0

## Bug Description

The SSG tool does not support programmatic generation and deletion of the `./dist` directory. If the `./directory` that comes with the project is deleted, relocated, or renamed, the program throws a compiler error and crashes.

The following compiler error is thrown when the `./dist` directory is deleted from the program's files:

```
{ _: [], i: '/Users/TD/Desktop/Silver Blaze.txt' }
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open './dist/Silver Blaze.html'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './dist/Silver Blaze.html'
}

```
## Expected Behaviour

I expect the program to generate `./dist` directory programmatically.  If the directory does not exist the program should generate it. If it already exists with content, the `./dist` directory should be deleted and recreated.  

## To Reproduce

1. Delete the `./dist` directory from the application files
2. Run: `node ./staticSiteCon --input /path-to-file/my-file.txt`

## Potential Fix

- Use the `fs` node module to check if the `./dist` directory exists using `fs.existsSync` function
- Use the `fs.rm` function to `recursively` delete an existing `./dist` directory
- Use either `fs.mkdir` or `fs.mkdirSync` to create the `./dist` directory

**Comment by cychu42** [comment]
Thank you for the helpful suggestion. The feature is now added.
