### ISSUE TITLE
Add support for outputting success/error messages to terminal

### ISSUE THREAD

**Issue by SerpentBytes** [cychu42/staticSiteCon#6]
## Operating Environment 

Operation System: macOS Monterey
Node version: v16.17.0

## Bug Description

Running the SSG tool with an invalid option does not generate an error message. Also, the tool does not generate any success messages, so there is no way to know whether HTML pages were successfully generated without having to manually check the `./dist` folder.

See below:

<img width="378" alt="Screen Shot 2022-09-15 at 8 35 27 AM" src="https://user-images.githubusercontent.com/50856799/190405342-837aa5f1-347a-40d9-aa71-c8e8f2919cd1.png">

## Expected Behaviour

Running the tool with an invalid option should generate an error message. 

## To Reproduce

- Run `node ./staticSiteCon --hello` or `node ./staticSiteCon -z`

## Potential Fix

-  Modify the `if` block that checks for option argument type, to include `else-if` and  `else` blocks. Alternatively, you can use a `switch` statement.

**Comment by cychu42** [comment]
Thank you. I added support for telling the user about what happens for successful executions, as well as messages for invalid options and other errors, such as empty input folder.
